# --- Atributos Padrão ---
DEFAULT_ATRIBUTOS = {
    # Saque (3)
    "vel_saque": 60,
    "pre_saque": 60,
    "segundo_saque": 60,
    # Retorno (1)
    "retorno": 60,
    # Groundstrokes (2)
    "forehand": 60,
    "backhand": 60,
    # Rede (3)
    "voleio": 60,
    "smash": 60,
    "lob": 60,
    # Estilo (3)
    "topspin": 60,
    "slice": 60,
    "winner": 60,
    # Físico (5)
    "velocidade": 60,
    "aceleracao": 60,
    "resistencia": 60,
    "forca": 60,
    "agilidade": 60,
    # Duplas — excluído do OVR simples (1)
    "duplas": 60,
}

DEFAULT_ATRIBUTOS_PSICOLOGICOS = {
    "clutch": 50,
    "consistencia": 50,
    "leitura_de_jogo": 50,
    "determinacao": 50,
    "compostura": 50,
    "agressividade": 50,
}

# --- Arquétipos Mentais ---
MENTAL_ARCHETYPES = {
    "1": {
        "nome": "Gelo nas Veias",
        "descricao": "Foco imperturbável e calma sob pressão.",
        "atributos": {
            "clutch": 80,
            "compostura": 75,
            "agressividade": 40,
            "leitura_de_jogo": 60,
            "determinacao": 65,
            "consistencia": 70,
        },
    },
    "2": {
        "nome": "Guerreiro",
        "descricao": "Nunca desiste de uma bola e luta até o fim.",
        "atributos": {
            "clutch": 60,
            "compostura": 55,
            "agressividade": 50,
            "leitura_de_jogo": 50,
            "determinacao": 85,
            "consistencia": 65,
        },
    },
    "3": {
        "nome": "Agressivo",
        "descricao": "Busca o winner e dita o ritmo, mas corre riscos.",
        "atributos": {
            "clutch": 55,
            "compostura": 50,
            "agressividade": 80,
            "leitura_de_jogo": 45,
            "determinacao": 65,
            "consistencia": 40,
        },
    },
    "4": {
        "nome": "Estrategista",
        "descricao": "Lê o adversário perfeitamente e antecipa jogadas.",
        "atributos": {
            "clutch": 65,
            "compostura": 60,
            "agressividade": 45,
            "leitura_de_jogo": 80,
            "determinacao": 55,
            "consistencia": 65,
        },
    },
    "5": {
        "nome": "Consistente",
        "descricao": "Sólido e confiável, erra pouco e resiste ao longo dos sets.",
        "atributos": {
            "clutch": 60,
            "compostura": 65,
            "agressividade": 40,
            "leitura_de_jogo": 60,
            "determinacao": 65,
            "consistencia": 82,
        },
    },
}

# --- Arquétipos de Jogador ---
ARCHETYPES = {
    "1": {
        "nome": "Serrador",
        "descricao": "Saque dominante e jogo de rede agressivo.",
        "atributos": {
            "vel_saque": 86,
            "pre_saque": 78,
            "segundo_saque": 70,
            "retorno": 56,
            "forehand": 62,
            "backhand": 58,
            "voleio": 84,
            "smash": 80,
            "lob": 60,
            "topspin": 56,
            "slice": 65,
            "winner": 74,
            "velocidade": 68,
            "aceleracao": 70,
            "resistencia": 60,
            "forca": 72,
            "agilidade": 72,
            "duplas": 60,
        },
    },
    "2": {
        "nome": "Grinder",
        "descricao": "Resistência e consistência no fundo de quadra.",
        "atributos": {
            "vel_saque": 60,
            "pre_saque": 64,
            "segundo_saque": 70,
            "retorno": 84,
            "forehand": 72,
            "backhand": 76,
            "voleio": 54,
            "smash": 58,
            "lob": 74,
            "topspin": 84,
            "slice": 72,
            "winner": 58,
            "velocidade": 74,
            "aceleracao": 68,
            "resistencia": 88,
            "forca": 64,
            "agilidade": 74,
            "duplas": 60,
        },
    },
    "3": {
        "nome": "Atacante de Fundo",
        "descricao": "Golpes poderosos e winners frequentes do fundo.",
        "atributos": {
            "vel_saque": 72,
            "pre_saque": 68,
            "segundo_saque": 65,
            "retorno": 72,
            "forehand": 86,
            "backhand": 76,
            "voleio": 58,
            "smash": 62,
            "lob": 64,
            "topspin": 74,
            "slice": 64,
            "winner": 86,
            "velocidade": 72,
            "aceleracao": 70,
            "resistencia": 66,
            "forca": 76,
            "agilidade": 66,
            "duplas": 60,
        },
    },
    "4": {
        "nome": "All-Court",
        "descricao": "Tudo equilibrado, sem pontos fracos evidentes.",
        "atributos": {
            "vel_saque": 70,
            "pre_saque": 70,
            "segundo_saque": 68,
            "retorno": 70,
            "forehand": 70,
            "backhand": 70,
            "voleio": 70,
            "smash": 70,
            "lob": 70,
            "topspin": 70,
            "slice": 70,
            "winner": 70,
            "velocidade": 70,
            "aceleracao": 70,
            "resistencia": 70,
            "forca": 68,
            "agilidade": 70,
            "duplas": 60,
        },
    },
    "5": {
        "nome": "Net Specialist",
        "descricao": "Domínio absoluto na rede, voleios e smashes letais.",
        "atributos": {
            "vel_saque": 70,
            "pre_saque": 68,
            "segundo_saque": 64,
            "retorno": 58,
            "forehand": 64,
            "backhand": 60,
            "voleio": 90,
            "smash": 86,
            "lob": 66,
            "topspin": 56,
            "slice": 68,
            "winner": 76,
            "velocidade": 74,
            "aceleracao": 78,
            "resistencia": 58,
            "forca": 66,
            "agilidade": 84,
            "duplas": 60,
        },
    },
}

# --- Fases de Torneio (T17) ---
FASES_NOMES = {
    "qualy_1": "1ª Rodada Quali",
    "qualy_2": "2ª Rodada Quali",
    "qualy_r1": "1ª Rodada Quali",
    "qualy_r2": "2ª Rodada Quali",
    "qualy_r3": "3ª Rodada Quali",
    "pre_oitavas": "32 avos",
    "oitavas": "Oitavas",
    "quartas": "Quartas",
    "semifinal": "Semifinal",
    "final": "Final",
    "campeao": "Campeão",
    "r128": "1ª Rodada",
    "r96": "1ª Rodada",
    "r64": "2ª Rodada",
    "r32": "3ª Rodada",
    "r16": "Oitavas",
}
