# === PROFISSIONAIS DISPONIVEIS ===
# equipe[*] = {"id": str, "semanas_restantes": int, "salario": int}
PROFISSIONAIS_DISPONIVEIS = {
    "treinador_fundo_jr": {
        "nome": "Pedro Vargas",
        "nacionalidade": "ARG",
        "categoria": "treinador",
        "estilo": "Fundo de Quadra",
        "estrelas": 2,
        "salario_semanal": 200,
        "bonus_progressao": 0.10,
        "foco_atributos": ["forehand", "backhand", "topspin", "movimento"],
        "bonus_recuperacao": 3,
        "bonus_xp": 1.1,
        "descricao": "Especialista em groundstrokes e base solida de fundo.",
    },
    "treinador_fundo_pro": {
        "nome": "Carlos Herrera",
        "nacionalidade": "ESP",
        "categoria": "treinador",
        "estilo": "Fundo de Quadra",
        "estrelas": 3,
        "salario_semanal": 600,
        "bonus_progressao": 0.20,
        "foco_atributos": ["forehand", "backhand", "topspin", "movimento"],
        "bonus_recuperacao": 7,
        "bonus_xp": 1.2,
        "descricao": "Experiente no circuito ATP, foco em rallies longos.",
    },
    "treinador_fundo_elite": {
        "nome": "Rafael Moya",
        "nacionalidade": "ESP",
        "categoria": "treinador",
        "estilo": "Fundo de Quadra",
        "estrelas": 4,
        "salario_semanal": 1800,
        "bonus_progressao": 0.35,
        "foco_atributos": ["forehand", "backhand", "topspin", "movimento"],
        "bonus_recuperacao": 15,
        "bonus_xp": 1.4,
        "descricao": "Moldou campeoes de Grand Slam em saibro.",
    },
    "treinador_rede_jr": {
        "nome": "Jack Williams",
        "nacionalidade": "AUS",
        "categoria": "treinador",
        "estilo": "Servico e Rede",
        "estrelas": 2,
        "salario_semanal": 200,
        "bonus_progressao": 0.10,
        "foco_atributos": ["saque", "voleio", "slice", "lob"],
        "bonus_recuperacao": 3,
        "bonus_xp": 1.1,
        "descricao": "Foca em servir bem e dominar a rede.",
    },
    "treinador_rede_pro": {
        "nome": "Stefan Mueller",
        "nacionalidade": "AUT",
        "categoria": "treinador",
        "estilo": "Servico e Rede",
        "estrelas": 3,
        "salario_semanal": 600,
        "bonus_progressao": 0.20,
        "foco_atributos": ["saque", "voleio", "slice", "lob"],
        "bonus_recuperacao": 7,
        "bonus_xp": 1.2,
        "descricao": "Especialista em tatica de saque e voleio.",
    },
    "treinador_rede_elite": {
        "nome": "Pete Andrews",
        "nacionalidade": "USA",
        "categoria": "treinador",
        "estilo": "Servico e Rede",
        "estrelas": 4,
        "salario_semanal": 1800,
        "bonus_progressao": 0.35,
        "foco_atributos": ["saque", "voleio", "slice", "lob"],
        "bonus_recuperacao": 15,
        "bonus_xp": 1.4,
        "descricao": "Treinou servidores entre os 10 melhores do mundo.",
    },
    "treinador_tatico_jr": {
        "nome": "Luca Bianchi",
        "nacionalidade": "ITA",
        "categoria": "treinador",
        "estilo": "Tatico",
        "estrelas": 2,
        "salario_semanal": 200,
        "bonus_progressao": 0.10,
        "foco_atributos": ["winner", "fisico", "forehand", "backhand"],
        "bonus_recuperacao": 3,
        "bonus_xp": 1.1,
        "descricao": "Foca em leitura de jogo e pontos diretos.",
    },
    "treinador_tatico_pro": {
        "nome": "Ivan Petrov",
        "nacionalidade": "CZE",
        "categoria": "treinador",
        "estilo": "Tatico",
        "estrelas": 3,
        "salario_semanal": 600,
        "bonus_progressao": 0.20,
        "foco_atributos": ["winner", "fisico", "forehand", "backhand"],
        "bonus_recuperacao": 7,
        "bonus_xp": 1.2,
        "descricao": "Especialista em variacao tatica e pressao.",
    },
    "treinador_lendario": {
        "nome": "Andre Champion",
        "nacionalidade": "FRA",
        "categoria": "treinador",
        "estilo": "Lendario",
        "estrelas": 5,
        "salario_semanal": 5000,
        "bonus_progressao": 0.30,
        "foco_atributos": [],
        "bonus_recuperacao": 20,
        "bonus_xp": 2.0,
        "descricao": "Ex-campeao de Grand Slam. Potencializa todo o seu jogo.",
    },
    "psi_junior": {
        "nome": "Sara Novak",
        "nacionalidade": "CZE",
        "categoria": "psicologo",
        "estilo": "Psicologo",
        "estrelas": 2,
        "salario_semanal": 150,
        "chance_mental": 0.20,
        "bonus_mental": 1,
        "descricao": "Ajuda a manter o foco nas derrotas.",
    },
    "psi_senior": {
        "nome": "Thomas Klein",
        "nacionalidade": "GER",
        "categoria": "psicologo",
        "estilo": "Psicologo",
        "estrelas": 3,
        "salario_semanal": 450,
        "chance_mental": 0.45,
        "bonus_mental": 1,
        "descricao": "Trabalha resiliencia e concentracao com jogadores ATP.",
    },
    "psi_master": {
        "nome": "Amelia Rossi",
        "nacionalidade": "ITA",
        "categoria": "psicologo",
        "estilo": "Psicologo",
        "estrelas": 4,
        "salario_semanal": 1200,
        "chance_mental": 0.70,
        "bonus_mental": 2,
        "descricao": "Referencia em psicologia esportiva de alto rendimento.",
    },
    "prep_jr": {
        "nome": "Marco Santos",
        "nacionalidade": "BRA",
        "categoria": "preparador",
        "estilo": "Preparador Fisico",
        "estrelas": 2,
        "salario_semanal": 150,
        "bonus_fadiga": 0,
        "bonus_fisico_pct": 0.05,
        "descricao": "Foco em condicionamento e prevencao basica.",
    },
    "prep_pro": {
        "nome": "James Cooper",
        "nacionalidade": "USA",
        "categoria": "preparador",
        "estilo": "Preparador Fisico",
        "estrelas": 3,
        "salario_semanal": 500,
        "bonus_fadiga": 0,
        "bonus_fisico_pct": 0.12,
        "descricao": "Treino funcional focado em resistencia e velocidade.",
    },
    "prep_elite": {
        "nome": "Yuki Tanaka",
        "nacionalidade": "JPN",
        "categoria": "preparador",
        "estilo": "Preparador Fisico",
        "estrelas": 4,
        "salario_semanal": 1500,
        "bonus_fadiga": 0,
        "bonus_fisico_pct": 0.25,
        "descricao": "Metodo de elite para manutencao de pico fisico.",
    },
    "mkt_freelancer": {
        "nome": "Sofia Lima",
        "nacionalidade": "BRA",
        "categoria": "marketing",
        "estilo": "Marketing",
        "estrelas": 2,
        "salario_semanal": 100,
        "seguidores_min": 500,
        "seguidores_max": 1500,
        "descricao": "Gerencia redes sociais basicas.",
    },
    "mkt_agencia": {
        "nome": "Kevin Park",
        "nacionalidade": "KOR",
        "categoria": "marketing",
        "estilo": "Marketing",
        "estrelas": 3,
        "salario_semanal": 400,
        "seguidores_min": 2000,
        "seguidores_max": 5000,
        "descricao": "Campanha profissional de midia esportiva.",
    },
    "mkt_star": {
        "nome": "Isabella Moore",
        "nacionalidade": "USA",
        "categoria": "marketing",
        "estilo": "Marketing",
        "estrelas": 4,
        "salario_semanal": 1200,
        "seguidores_min": 6000,
        "seguidores_max": 15000,
        "descricao": "Gerencia imagem de estrelas mundiais do esporte.",
    },
}

FISIOTERAPEUTAS_DISPONIVEIS = {
    "fisio_jr": {
        "nome": "Ana Rodrigues",
        "nacionalidade": "BRA",
        "categoria": "fisioterapeuta",
        "estilo": "Fisioterapeuta",
        "estrelas": 2,
        "salario_semanal": 180,
        "bonus_fadiga": 5,
        "bonus_recuperacao_lesao": 1,
        "descricao": "Tecnicas de recuperacao e prevencao basica.",
    },
    "fisio_pro": {
        "nome": "Hiroshi Yamada",
        "nacionalidade": "JPN",
        "categoria": "fisioterapeuta",
        "estilo": "Fisioterapeuta",
        "estrelas": 3,
        "salario_semanal": 600,
        "bonus_fadiga": 12,
        "bonus_recuperacao_lesao": 2,
        "descricao": "Fisioterapia esportiva avancada para atletas ATP.",
    },
    "fisio_elite": {
        "nome": "Victoria Walsh",
        "nacionalidade": "GBR",
        "categoria": "fisioterapeuta",
        "estilo": "Fisioterapeuta",
        "estrelas": 4,
        "salario_semanal": 1800,
        "bonus_fadiga": 20,
        "bonus_recuperacao_lesao": 3,
        "descricao": "Referencia mundial em recuperacao de atletas de elite.",
    },
}

EMPRESARIOS_DISPONIVEIS = {
    "empresario_jr": {
        "nome": "Roberto Carvalho",
        "nacionalidade": "BRA",
        "categoria": "empresario",
        "estrelas": 2,
        "salario_semanal": 300,
        "max_equipe": 3,
        "bonus_patrocinio": 0.05,
        "descricao": "Gerencia contratos basicos e consegue ate 3 profissionais.",
    },
    "empresario_pro": {
        "nome": "Marcus Chen",
        "nacionalidade": "USA",
        "categoria": "empresario",
        "estrelas": 3,
        "salario_semanal": 800,
        "max_equipe": 4,
        "bonus_patrocinio": 0.15,
        "descricao": "Experiencia em negociacoes ATP. Libera ate 4 profissionais.",
    },
    "empresario_elite": {
        "nome": "David Thornton",
        "nacionalidade": "GBR",
        "categoria": "empresario",
        "estrelas": 4,
        "salario_semanal": 2000,
        "max_equipe": 5,
        "bonus_patrocinio": 0.30,
        "descricao": "Gerenciou Top 10. Libera ate 5 profissionais.",
    },
}

PROFISSIONAIS_DISPONIVEIS.update(FISIOTERAPEUTAS_DISPONIVEIS)
