from src.constants.torneio_constants import (
    BEST_OF_GRAND_SLAM,
    BEST_OF_PADRAO,
    NUM_ROUNDS_GRAND_SLAM,
    NUM_ROUNDS_ATP_1000,
    NUM_ROUNDS_PADRAO,
    DRAW_SIZE_GRAND_SLAM,
    DRAW_SIZE_ATP_1000,
    DRAW_SIZE_PADRAO,
    QUALY_VAGAS_GRAND_SLAM,
    QUALY_VAGAS_ATP_1000,
    QUALY_VAGAS_PADRAO,
    QUALY_JOGADORES_GRAND_SLAM,
    QUALY_JOGADORES_ATP_1000,
    QUALY_JOGADORES_PADRAO,
    NUM_TOP_DIRETOS_GRAND_SLAM,
    NUM_TOP_DIRETOS_ATP_1000,
    NUM_TOP_DIRETOS_PADRAO,
    WILDCARDS_GRAND_SLAM,
    WILDCARDS_ATP_1000,
    WILDCARDS_ATP_500,
    WILDCARDS_PADRAO,
)

TOURNAMENT_PROFILES = {
    "grand_slam": {
        "best_of_sets_masculino": BEST_OF_GRAND_SLAM,
        "best_of_sets_feminino": BEST_OF_PADRAO,
        "num_rounds": NUM_ROUNDS_GRAND_SLAM,
        "draw_size_main": DRAW_SIZE_GRAND_SLAM,
        "draw_size_first_main_phase": DRAW_SIZE_GRAND_SLAM,
        "draw_size_atualizar_fase_merge": DRAW_SIZE_GRAND_SLAM,
        "main_draw_first_phase": "r128",
        "qualy_phases": ["qualy_r1", "qualy_r2", "qualy_r3"],
        "main_draw_phases": [
            "r128",
            "r64",
            "r32",
            "r16",
            "quartas",
            "semifinal",
            "final",
        ],
        "vagas_qualy": QUALY_VAGAS_GRAND_SLAM,
        "num_jogadores_qualy": QUALY_JOGADORES_GRAND_SLAM,
        "num_top_diretos": NUM_TOP_DIRETOS_GRAND_SLAM,
        "wildcards": WILDCARDS_GRAND_SLAM,
        "merge_transitions": {("qualy_r3", "r128")},
        "usa_entrada_direta_ranqueados": False,
    },
    "atp_1000": {
        "best_of_sets_masculino": BEST_OF_PADRAO,
        "best_of_sets_feminino": BEST_OF_PADRAO,
        "num_rounds": NUM_ROUNDS_ATP_1000,
        "draw_size_main": DRAW_SIZE_ATP_1000,
        "draw_size_first_main_phase": DRAW_SIZE_ATP_1000,
        "draw_size_atualizar_fase_merge": DRAW_SIZE_ATP_1000,
        "main_draw_first_phase": "r96",
        "qualy_phases": ["qualy_1", "qualy_2"],
        "main_draw_phases": [
            "r96",
            "r64",
            "r32",
            "r16",
            "quartas",
            "semifinal",
            "final",
        ],
        "vagas_qualy": QUALY_VAGAS_ATP_1000,
        "num_jogadores_qualy": QUALY_JOGADORES_ATP_1000,
        "num_top_diretos": NUM_TOP_DIRETOS_ATP_1000,
        "wildcards": WILDCARDS_ATP_1000,
        "merge_transitions": {("qualy_2", "r96"), ("r96", "r64")},
        "usa_entrada_direta_ranqueados": False,
    },
    "atp_padrao": {
        "best_of_sets_masculino": BEST_OF_PADRAO,
        "best_of_sets_feminino": BEST_OF_PADRAO,
        "num_rounds": NUM_ROUNDS_PADRAO,
        "draw_size_main": DRAW_SIZE_PADRAO,
        "draw_size_first_main_phase": DRAW_SIZE_PADRAO,
        "draw_size_atualizar_fase_merge": DRAW_SIZE_PADRAO,
        "main_draw_first_phase": "pre_oitavas",
        "qualy_phases": ["qualy_1", "qualy_2"],
        "main_draw_phases": ["pre_oitavas", "oitavas", "quartas", "semifinal", "final"],
        "vagas_qualy": QUALY_VAGAS_PADRAO,
        "num_jogadores_qualy": QUALY_JOGADORES_PADRAO,
        "num_top_diretos": NUM_TOP_DIRETOS_PADRAO,
        "wildcards": WILDCARDS_PADRAO,
        "merge_transitions": {("qualy_2", "pre_oitavas")},
        "usa_entrada_direta_ranqueados": True,
    },
    "challenger_125": {
        "best_of_sets_masculino": BEST_OF_PADRAO,
        "best_of_sets_feminino": BEST_OF_PADRAO,
        "num_rounds": 6,
        "draw_size_main": 48,
        "draw_size_first_main_phase": 48,
        "draw_size_atualizar_fase_merge": 48,
        "main_draw_first_phase": "r48",
        "qualy_phases": ["qualy_1", "qualy_2"],
        "main_draw_phases": ["r48", "r32", "r16", "quartas", "semifinal", "final"],
        "vagas_qualy": 6,
        "num_jogadores_qualy": 24,
        "num_top_diretos": 38,
        "wildcards": 4,
        "merge_transitions": {("qualy_2", "r48"), ("r48", "r32")},
        "usa_entrada_direta_ranqueados": True,
    },
    "itf_100": {
        "best_of_sets_masculino": BEST_OF_PADRAO,
        "best_of_sets_feminino": BEST_OF_PADRAO,
        "num_rounds": NUM_ROUNDS_PADRAO,
        "draw_size_main": DRAW_SIZE_PADRAO,
        "draw_size_first_main_phase": DRAW_SIZE_PADRAO,
        "draw_size_atualizar_fase_merge": DRAW_SIZE_PADRAO,
        "main_draw_first_phase": "pre_oitavas",
        "qualy_phases": ["qualy_1", "qualy_2"],
        "main_draw_phases": ["pre_oitavas", "oitavas", "quartas", "semifinal", "final"],
        "vagas_qualy": QUALY_VAGAS_PADRAO,
        "num_jogadores_qualy": QUALY_JOGADORES_PADRAO,
        "num_top_diretos": NUM_TOP_DIRETOS_PADRAO,
        "wildcards": WILDCARDS_PADRAO,
        "merge_transitions": {("qualy_2", "pre_oitavas")},
        "usa_entrada_direta_ranqueados": True,
    },
    "itf_25": {
        "best_of_sets_masculino": BEST_OF_PADRAO,
        "best_of_sets_feminino": BEST_OF_PADRAO,
        "num_rounds": NUM_ROUNDS_PADRAO,
        "draw_size_main": DRAW_SIZE_PADRAO,
        "draw_size_first_main_phase": DRAW_SIZE_PADRAO,
        "draw_size_atualizar_fase_merge": DRAW_SIZE_PADRAO,
        "main_draw_first_phase": "pre_oitavas",
        "qualy_phases": ["qualy_1", "qualy_2"],
        "main_draw_phases": ["pre_oitavas", "oitavas", "quartas", "semifinal", "final"],
        "vagas_qualy": QUALY_VAGAS_PADRAO,
        "num_jogadores_qualy": QUALY_JOGADORES_PADRAO,
        "num_top_diretos": NUM_TOP_DIRETOS_PADRAO,
        "wildcards": WILDCARDS_PADRAO,
        "merge_transitions": {("qualy_2", "pre_oitavas")},
        "usa_entrada_direta_ranqueados": True,
    },
    "atp_finals": {
        "best_of_sets_masculino": BEST_OF_PADRAO,
        "best_of_sets_feminino": BEST_OF_PADRAO,
        "num_rounds": 3,
        "draw_size_main": 8,
        "draw_size_first_main_phase": 8,
        "draw_size_atualizar_fase_merge": 8,
        "main_draw_first_phase": "quartas",
        "qualy_phases": [],
        "main_draw_phases": ["quartas", "semifinal", "final"],
        "vagas_qualy": 0,
        "num_jogadores_qualy": 0,
        "num_top_diretos": 8,
        "wildcards": 0,
        "merge_transitions": set(),
        "usa_entrada_direta_ranqueados": False,
    },
}

ENTRY_DIRECT_SELECTORS = {
    "ATP 250": "_selecionar_entrada_direta_padrao",
    "ATP 500": "_selecionar_entrada_direta_padrao",
    "Challenger 125": "_selecionar_entrada_direta_padrao",
    "ITF 100": "_selecionar_entrada_direta_padrao",
    "ITF 25": "_selecionar_entrada_direta_padrao",
    "ATP Finals": "_selecionar_campo_finals",
    "WTA Finals": "_selecionar_campo_finals",
}

WILDCARD_POLICIES = {
    "ATP 250": "locais_prioritarios",
    "default": "ranking_com_pais_sede",
}

WILDCARD_OVERRIDES = {
    "ATP 500": WILDCARDS_ATP_500,
}
